---
abstract: "Create an adjunct \"Doc\" accessor of a column's data which is automatically parsed into a LibXML documentElement (beta-software, dev release)."
author:
  - 'Ashley Pond V C<< <ashley@cpan.org> >>.'
build_requires:
  Test::More: 0.5
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-LibXMLdoc
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Entities: 0
  XML::LibXML: 1.63
  parent: 0
version: 0.03_a
